### ISSUE TITLE
bug: crash bug, examining "stealth system" implant

### ISSUE THREAD

**Issue by veryinky** [jwvhewitt/gearhead-1#20]
![crash bug](https://cloud.githubusercontent.com/assets/3881388/14586777/41a6fb50-0471-11e6-8408-87467ed8d2ee.png)

[RPGAngela.txt](https://github.com/jwvhewitt/gearhead-1/files/222626/RPGAngela.txt)

How to replicate:
1. open field HQ
2. examine "steal system" implant

Included save game. No idea where stealth system implant came from, it was on the world map.

**Comment by jwvhewitt** [comment]
Two bugs fixed. First, the mecha part editor will no longer crash when examining an item with zero mass. Second, the Tech Vulture talent will not grab non-extractable parts. The stealth system was taken from a Domino mecha via the Tech Vulture talent, but since it's an integral part that should not have been possible.
